### ISSUE TITLE
Setup cvat

### ISSUE THREAD

**Issue by frunika** [OpenTrafficCam/OTLabels#5]
[cvat](https://github.com/openvinotoolkit/cvat)

**Comment by frunika** [comment]
A cvat instance is now running at (label.opentrafficcam.org).

It's running in a docker container on a local workstation behind the default QuerPlaner reverse proxy.

I added some options in `docker-compose.override.yml`

```
version: '3.3'

services:
  cvat:
    environment:
      CVAT_SHARE_URL: 'Mounted from /mnt/d/cvat_share host directory'
    volumes:
      - /mnt/d/cvat_share:/home/django/share:ro

  cvat_proxy:
    environment:
      CVAT_HOST: label.opentrafficcam.org
```

To disable self-register of new users i changed `cvat/settings/base.py` and added the need for e-mail verification.
[Source](https://github.com/openvinotoolkit/cvat/issues/1283#issuecomment-753302465)

```py
# https://github.com/pennersr/django-allauth
# ACCOUNT_EMAIL_VERIFICATION = 'none'
ACCOUNT_AUTHENTICATION_METHOD = 'username'
ACCOUNT_CONFIRM_EMAIL_ON_GET = True
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
```

To start-up run

```bash
docker-compose -f docker-compose.yml -f components/analytics/docker-compose.analytics.yml -f docker-compose.override.yml build
docker-compose -f docker-compose.yml -f components/analytics/docker-compose.analytics.yml -f docker-compose.override.yml up -d
```
